# ==========================================
#   Template Project
#   Copyright (c) 2014 Chase Johnson
# ========================================== 


#Hack to call the main make file. This was to keep the project files out of the 
#main root directory
include ..//Makefile